name: Test and lint

on:
  push:
    paths:
      - '**.py'
      - '.github/workflows/**'
      - '.flake8'
      - 'poetry.lock'
      - 'pyproject.toml'
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
    paths:
      - '**.py'
      - '.github/workflows/**'
      - '.flake8'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: 3.11.3
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi
      - name: Black check
        run: |
          black . --check
      - name: Isort check
        run: |
          isort . --check -q
      - name: Lint with flake8
        run: |
          flake8 . --format="::error file=%(path)s,line=%(row)d,col=%(col)d::%(path)s:%(row)d:%(col)d: %(code)s %(text)s"
